---
# tasks file for gitlab-runner

- include: pre-install.yml
  tags:
    - pre-install

- include: install.yml
  tags:
    - install
    - update

- include: global-setup.yml
  tags:
    - configure

# - include: register.yml
#   tags:
#     - register
